### PR TITLE
[Tutorial/Basic] #60 networking

### PR DESCRIPTION
**Pull request by qkreltms**
## Changes
  Added networking section of code.
  **Plus**: I'm considering to add  https://github.com/axios/axios#cancellation for more detail explanation of axios.
### References
#60

Reviewers: @sonypark, @Haerang94

### CODE REVIEW

**Comment by sonypark** [comment]
Ok it looks good to me, I think you can keep working on this progress

**Comment by JeffGuKang** [comment]
Good job. Do not forget to use capital letter for first character of you commit messages.

**Comment by qkreltms** [comment]
@sonypark, @Haerang94 Please review my code and let me know if there is something to change.

**Comment by sonypark** [comment]
I think it there is not a big thing to change.

**Pull request merged**
