### PR TITLE
Add: state tutorial base

### PR DESCRIPTION
**Pull request by voidmatcha**

### CODE REVIEW

**Comment by JeffGuKang** [comment]
How about move to the `Examples/StateManagement/` directory? 
For examples, 
- `Examples/StateManagement/Teamplate`
- `Examples/StateManagement/ContextCounter`

**Comment by JeffGuKang** [comment]
@dididy  
Could you change project name `setState` to `SetState`?

**Review by JeffGuKang — COMMENTED** [review]
Could you change project name setState to SetState?
Project name `setState` => `SetState`

**Comment by voidmatcha** [comment]
Okay I'll change it!

**Review by JeffGuKang — APPROVED** [review]

**Pull request merged**
