### PR TITLE
Translated documents into Korean 

### PR DESCRIPTION
**Pull request by chococrunch2021**
## Fix #
- Typo correction was added.
- Fixed the path of links.

## Changes
- Added Korean version documents.
- Translated basic-settings English document.
- Added additional contents to improve-user-interface document

#### (Automated Tests)
- N/A

#### (Manual Tests)
- N/A

### Notes
- It can be updated again.

### References
- https://facebook.github.io/react-native/

### CODE REVIEW

**Comment by chococrunch2021** [comment]
Make some reviews to go to next step, please. Thanks. 
@JeffGuKang @sonypark

**Review by JeffGuKang — APPROVED** [review]

**Review by JeffGuKang — COMMENTED** [review]
Your 7aad606 commit with `Added Korean version files` looks to add a new example. It this the Korean version example?

**Review by JeffGuKang — CHANGES_REQUESTED** [review]
What is the `wide_your_tap` example?

**Comment by chococrunch2021** [comment]
> Your [7aad606](https://github.com/JeffGuKang/react-native-tutorial/commit/7aad606055ca7775713018411330e27ff24db42a) commit with `Added Korean version files` looks to add a new example. It this the Korean version example?

You can see Korean version files at the bottom. 
I made new example project and Korean version files together, so these two projects were committed together.

**Comment by chococrunch2021** [comment]
> What is the `wide_your_tap` example?

This is one of the example projects for improve-user-interface tutorial.

**Review by JeffGuKang — APPROVED** [review]

**Pull request merged**
